### ISSUE TITLE
Problem when trying to run roguelike-tutorial-1 example as a standalone project

### ISSUE THREAD

**Issue by anmej** [tomassedovic/tcod-rs#200]
Hello.

I cloned the whole tcod-rs, and the example runs. However, when I use exactly the same code as a standalone cargo project, I get this:

```
src/rl1.rs:26:9: 26:43 error: `Key` does not name a struct or a struct variant [E0163]
src/rl1.rs:26         Key { code: Enter, alt: true, .. } => {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/rl1.rs:30:9: 30:33 error: `Key` does not name a struct or a struct variant [E0163]
src/rl1.rs:30         Key { code: Escape, .. } => {
                      ^~~~~~~~~~~~~~~~~~~~~~~~
src/rl1.rs:34:9: 34:29 error: `Key` does not name a struct or a struct variant [E0163]
src/rl1.rs:34         Key { code: Up, .. } => *player_y -= 1,
                      ^~~~~~~~~~~~~~~~~~~~
src/rl1.rs:35:9: 35:31 error: `Key` does not name a struct or a struct variant [E0163]
src/rl1.rs:35         Key { code: Down, .. } => *player_y += 1,
                      ^~~~~~~~~~~~~~~~~~~~~~
src/rl1.rs:36:9: 36:31 error: `Key` does not name a struct or a struct variant [E0163]
src/rl1.rs:36         Key { code: Left, .. } => *player_x -= 1,
                      ^~~~~~~~~~~~~~~~~~~~~~
src/rl1.rs:37:9: 37:32 error: `Key` does not name a struct or a struct variant [E0163]
src/rl1.rs:37         Key { code: Right, .. } => *player_x += 1,
```

The code is the same, so the problem must be somewhere else. In my Cargo.toml I had:
```
[dependencies]
rand = "*"
tcod = "*"
```
Following this, I tried cloning your roguelike-tutorial repo. It works fine. So I tried to change the Cargo.toml of the standalone project to this:
```
[dependencies.tcod]
git = "https://github.com/tomassedovic/tcod-rs"
features = ["rustc-serialize"]

[dependencies]
rand = "*"
```

And now it works. Do you have any idea what's going on? Are git and crates.io versions different?

PS. Thank you for doing awesome works. I wanted to write an roguelike in Rust for a while, and with your help I might just do it...

**Comment by tomassedovic** [comment]
Hey, I'm on a train now but I'll have a look in a few hours. Yeah the
version on creates.io is a bit old now. I wanted to push another release
but didn't get to it yet.

Also, you may want to check the
https://github.com/tomassedovic/roguelike-tutorial/

I've moved the work there because it makes more sense as a standalone repo.
And that should be pretty much the complete port of the Python tutorial
code, but without the accompanying text yet.

And thanks :-)

**Comment by anmej** [comment]
>Hey, I'm on a train now but I'll have a look in a few hours. Yeah the version on creates.io is a bit old now. I wanted to push another release but didn't get to it yet.

This is probably why some examples work, and some don't.

>Also, you may want to check the https://github.com/tomassedovic/roguelike-tutorial/

Oh yes, this is most awesome, too. Are you planning to turn it into a full-blown tutorial?

**Comment by tomassedovic** [comment]
I do indeed! And sorry, I didn't notice you mentioned the repo in your first comment.

But just writing the code took me longer than I thought. It'll probably be a while before it's finished. I have a few things I want to clean up first, but it is functional. The tutorial tries to follow the same structure as the original Python one. but there are differences because Rust is quite different in some ways.

All the examples should work when you clone tcod-rs (that gets tested on every commit), but yeah, depending on the features, some won't work with the current crates.io version.

I could publish a new release now, but there have been some breaking changes and I have a couple more I want to do, so I'd like to just break things just once. Regardless, I'll do my best to get a new crates.io version up within the week.

**Comment by tomassedovic** [comment]
Version 0.8.0 has been pushed to crates.io. I'm closing this issue.
