### ISSUE TITLE
Support for libtcod 1.6.3+

### ISSUE THREAD

**Issue by huhlig** [tomassedovic/tcod-rs#249]
Any plans to support v1.6+?

**Comment by tomassedovic** [comment]
I'd love to, but I'm not going to be able to put the time in myself :-(

If you're interested, I can point you in the right direction.

**Comment by Tyruiop** [comment]
Hi, I noticed that I need to have glu (GL/glu.h) installed to build tcod (the actual library) which led me to find that the lib seems to be building with sdl1, not sdl2.

Is it connected to this issue? Because in libtcod 1.6 there is [this file](https://bitbucket.org/libtcod/libtcod/src/eb18c78ef811098b745552fa5a3350aa8d427840/README-linux-SDL2.md?at=default&fileviewer=file-view-default) which hints that it should build with sdl2.

If that's the case I can try to help with support for 1.6 (I'm quite new at rust but that would be a nice way to learn some more).

**Comment by tomassedovic** [comment]
@Tyruiop yeah so libtcod 1.6 only works with SDL 2 and libtcod 1.5 with SDL 1 (I don't think it works with SDL 2 as well but maybe?).

If you (or anyone else) is interested to try this, here's what it would entail:

1. updating the libtcod source checkout in tcod_sys: https://github.com/tomassedovic/tcod-rs/tree/master/tcod_sys/libtcod

(we carry the libtcod source there so it's not necessary to download it on build)

2. Update tcod_sys' build.rs to build the new libtcod: https://github.com/tomassedovic/tcod-rs/blob/master/tcod_sys/build.rs

3. update the tcod_sys/lib.rs file to reflect the libtcod 1.6 API changes:

https://github.com/tomassedovic/tcod-rs/blob/master/tcod_sys/lib.rs

I'm not sure how much has changed -- this might be a few manual additions or it may require running bindgen on the libtcod header files

4. Since it's almost certainly going to be a breaking change, update tcod_sys' version in Cargo.toml to "5.0.0"

https://github.com/tomassedovic/tcod-rs/blob/master/tcod_sys/Cargo.toml#L4

5. Try to build tcod-rs (which uses tcod_sys), fix any breakage and make sure all tests pass. Again, this will probably require a major version number change.

I'll help you with guidance and code review, but it's something that may end up taking a lot of time and effort so be prepared :-).

**Comment by Gustorn** [comment]
I actually started porting the library to 1.6 once but gave up due to a lack of time. The problems I ran into:

1. The new bindgen generates more typesafe code than the old one did. This would be nice but it also means that a lot of the wrapper types need some modification. If you can figure out how to turn off the "enumification" of constants in bindgen you'll probably save a lot of time 
2. I could only get it to build with either the OpenGL *or* the SDL2 backend, not both of them simultaneously
3. Figuring out what exactly the breaking changes are: [this changelog](https://bitbucket.org/libtcod/libtcod/src/eb18c78ef811098b745552fa5a3350aa8d427840/libtcod-CHANGELOG.txt) is probably your best bet

**Comment by Tyruiop** [comment]
@Gustorn do you have anywhere I could look at what you did so far?

In any case, I've been looking at points 1, 2, 3 in @tomassedovic answer and at least 2 shouldn't be too hard (I mean, I hope :p) because libtcod 1.6 has autotools for both unixes and windows, so I was thinking about using std::process::Command to invoke them (I will definitively need help with windows autotools because I don't have any windows computer at my disposal). Does that sound like a reasonable idea?

**Comment by Gustorn** [comment]
@Tyruiop It seems like I edited my post just a few minutes late. A link to my branch is in the previous post.

**Comment by Tyruiop** [comment]
Ok great!

The good news is that at least locally it builds we no trouble whatsoever (a few warning, deprecated things but nothing serious as far as I could tell), including the examples (I tried the samples one it worked flawlessly). Actually, now I'm wondering why you didn't make a PR?

**Comment by Gustorn** [comment]
The main thing was the opengl/sdl2 issue and I haven't looked at the changed APIs too carefully. I'll merge your changes then open a PR and we can see if there's anything that needs fixing

**Comment by zetashift** [comment]
@Tyruiop I can help with the windows testing!
