### ISSUE TITLE
Warnings from tcod-sys

### ISSUE THREAD

**Issue by jgilchrist** [tomassedovic/tcod-rs#76]
I'm getting warnings from tcod-sys about using `int` and `uint`. rust-bindgen was just updated to use `isize` and `usize` so now might be a good time to re-run it and update the bindings.

**Comment by tomassedovic** [comment]
Last time I tried running bindgen, it didn't work and then I managed to wipe my home dir debugging it (my stupidity and lack of checks in bindgen's build script, I think). But yeah, it'd be good to clear those warnings.

Speaking of tcod-sys. I think I've made a mistake setting its version to `1.5.2`. I wanted it to correspond to the libtcod binaries it links to, but crates.io expects crates to use Semantic Versioning, they'll get out of sync pretty quickly. E.g. this change will almost certainly need a bump to `2.0.0` because it'll be a breaking one.

Do you have any ideas how to deal with this? We can just roll with it, but maybe I'm missing a better solution.

**Comment by tomassedovic** [comment]
My `$HOME` survived the bindgen treatment this time! \o/

**Comment by jgilchrist** [comment]
Wow, oops. Good to hear it worked this time! Regarding the versioning, I can see the appeal of matching up to the binaries but I think it's probably easier not to fight the scheme crates.io expects, so 2.0 is probably the way to go.
